# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1dfad63c7a7e68cc97d62a033bbc15c560a82369cdbfdf82dc2d54650d89fb8321b97f7a53eea4917f4cc04dffad0270aab2d9632a0a227214f357985997ba4

test:
  secret_key_base: 39e4566ca56bdc95ab0efa2df4b4d922d0380a23c52727f4bea02f02b6a967520dfe1313ec34f6f3c2b426ea914fe84c448db542a4c802be013e9c1ed7276f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
